# Define here the models for your scraped items
#
# See documentation in:
# https://docs.scrapy.org/en/latest/topics/items.html

import scrapy


class EbayItem(scrapy.Item):
    record_create_dt = scrapy.Field()
    type = scrapy.Field()
    feed_code = scrapy.Field()
    site = scrapy.Field()
    name = scrapy.Field()
    currency = scrapy.Field()
    source_country = scrapy.Field()
    context_identifier = scrapy.Field()
    record_create_by = scrapy.Field()
    execution_id = scrapy.Field()
    specs = scrapy.Field()
    Condizione = scrapy.Field()
    Produktart = scrapy.Field()
    title = scrapy.Field()
    condition = scrapy.Field()
    starting_bid = scrapy.Field()
    total_bid = scrapy.Field()
    price = scrapy.Field()
    item_ranking = scrapy.Field()
    src = scrapy.Field()
    Colour = scrapy.Field()
    Tyre_Type = scrapy.Field()
    Model_Year = scrapy.Field()
    Condition = scrapy.Field()
    Shifter_Style = scrapy.Field()
    Handlebar_Type = scrapy.Field()
    Number_of_Speeds = scrapy.Field()
    Color = scrapy.Field()
    Wheel_Size = scrapy.Field()
    Suspension_Type = scrapy.Field()
    Bike_Type = scrapy.Field()
    Brand = scrapy.Field()
    Frame_Size = scrapy.Field()
    Material = scrapy.Field()
    Department = scrapy.Field()
    Model = scrapy.Field()
    Brake_Type = scrapy.Field()
    Tire_Type = scrapy.Field()
    MPN = scrapy.Field()
    page_number = scrapy.Field()
    Age_in_years = scrapy.Field()
    Vintage = scrapy.Field()
    url = scrapy.Field()
    Gear_Change_Mechanism = scrapy.Field()
    UPC = scrapy.Field()
    Frame_Number = scrapy.Field()
    Features = scrapy.Field()
    Item_Weight = scrapy.Field()
    Stem = scrapy.Field()
    Saddle = scrapy.Field()
    Drivetrain_Type = scrapy.Field()
    Seatpost = scrapy.Field()
    Gender = scrapy.Field()
    Crankset = scrapy.Field()
    Chainrings = scrapy.Field()
    Cassette = scrapy.Field()
    Wheel_Set = scrapy.Field()
    Front_Derailleur = scrapy.Field()
    Fork = scrapy.Field()
    Rear_Derailleur = scrapy.Field()
    Shifters = scrapy.Field()

